=== ryanwolhuter/the-happy-path/test/document-model-json-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "minLength": 1
    },
    "documentType": {
      "type": "string",
      "const": "my-org/test"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "fileExtension": {
      "type": "string",
      "const": ".test"
    },
    "state": {
      "type": "object",
      "properties": {
        "global": {
          "type": "object",
          "properties": {
            "globalStuff": {
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1
              }
            }
          },
          "required": [
            "globalStuff"
          ],
          "additionalProperties": false
        },
        "other": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "minLength": 1
            },
            "ids": {
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1
              }
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "names": {
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1
              }
            }
          },
          "required": [
            "id",
            "ids"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "global",
        "other"
      ],
      "additionalProperties": false
    },
    "$schema": {
      "type": "string",
      "const": "./document-model-json-schema.json"
    }
  },
  "required": [
    "id",
    "documentType",
    "name",
    "fileExtension",
    "state",
    "$schema"
  ],
  "additionalProperties": false
}

=== ryanwolhuter/the-happy-path/test/document-model.json
{
  "$schema": "./document-model-json-schema.json",
  "id": "123e4567-e89b-12d3-a456-426614174000",
  "name": "My Test Document Model",
  "documentType": "my-org/test",
  "fileExtension": ".test",
  "state": {
    "global": {
      "globalStuff": []
    },
    "other": {
      "id": "other",
      "ids": []
    }
  }
}
