=== ryanwolhuter/the-happy-path/src/TestStateSchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid",
      "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$"
    },
    "ids": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uuid",
        "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$"
      }
    },
    "name": {
      "type": "string"
    },
    "names": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "$schema": {
      "type": "string",
      "const": "./TestStateSchema.json"
    },
    "graphqlSchema": {
      "type": "string",
      "const": "type TestState {\n  id: ID!\n  ids: [ID!]!\n  name: String\n  names: [String]\n}\n"
    }
  },
  "required": [
    "id",
    "ids",
    "$schema",
    "graphqlSchema"
  ],
  "additionalProperties": false
}

=== ryanwolhuter/the-happy-path/src/Test-state.json
{
  "$schema": "./TestStateSchema.json",
  "id": "123e4567-e89b-12d3-a456-426614174000",
  "ids": [
    "123e4567-e89b-12d3-a456-426614174000",
    "123e4567-e89b-12d3-a456-426614174001"
  ],
  "name": "test",
  "names": [
    "test1",
    "test2"
  ],
  "graphqlSchema": "type TestState {\n  id: ID!\n  ids: [ID!]!\n  name: String\n  names: [String]\n}\n"
}
